name: Determine Build Configuration

on:
  workflow_call:
    inputs:
      trigger:            # 'release' or 'workflow_dispatch'
        type: string
        required: true
      target_branch:      # branch name (from release.target_commitish or ref_name)
        type: string
        required: true
      override_build_configuration:  # '', 'Release', or 'Debug' when manual
        type: string
        required: false
        default: ''
      prerelease:         # only meaningful when trigger == 'release'
        type: boolean
        required: false
        default: false
    outputs:
      build_configuration:
        description: "Resolved configuration (Release|Debug)"
        value: ${{ jobs.compute.outputs.build_configuration }}

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      build_configuration: ${{ steps.out.outputs.build_configuration }}
    steps:
      - id: out
        name: Decide build configuration
        run: |
          set -euo pipefail
          TRIGGER='${{ inputs.trigger }}'
          BRANCH='${{ inputs.target_branch }}'
          OVERRIDE='${{ inputs.override_build_configuration }}'
          PRERELEASE='${{ inputs.prerelease }}'

          if [[ -n "$OVERRIDE" ]]; then
            CFG="$OVERRIDE"
            echo "Manual override → $CFG"
          else
            if [[ "$TRIGGER" == "release" ]]; then
              if [[ "$PRERELEASE" == "false" ]]; then
                CFG="Release"
              else
                CFG="Debug"
              fi
              echo "Release event on '$BRANCH' (prerelease=$PRERELEASE) → $CFG"
            else
              # workflow_dispatch default: main => Release, else Debug
              if [[ "$BRANCH" == "main" ]]; then
                CFG="Release"
              else
                CFG="Debug"
              fi
              echo "workflow_dispatch on '$BRANCH' → default $CFG"
            fi
          fi

          echo "build_configuration=$CFG" >> "$GITHUB_OUTPUT"
