name: Old Publish

on:
  workflow_call:
    inputs:
      build_configuration:
        description: 'Build configuration'
        required: true
        type: string
        default: 'Release'
    secrets:
      NUGET_API_KEY:
        required: false

env:
  BRANCH_NAME: ${{ github.event.release.target_commitish }}
  SOLUTION_NAME: ${{ vars.SOLUTION_NAME }}
  DOTNET_VERSION: '9.0.x'
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check Build Configuration
      if: ${{ inputs.build_configuration == '' }}
      run: |
        echo "Invalid Build Configuration"
        exit 1

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Ensure Nerdbank.GitVersioning tool is installed
      run: |
        if ! dotnet tool list -g | grep -q nbgv; then
          dotnet tool install --global nbgv
        else
          dotnet tool update --global nbgv
        fi

    - name: Get version from Nerdbank.GitVersioning
      id: nbgv
      run: |
        nbgv get-version --format json > nbgv.json
        version=$(jq -r .NuGetPackageVersion nbgv.json)
        echo "version_tag=$version" >> $GITHUB_ENV

    - name: Get version from version.json
      id: get_version
      run: |
        version=$(jq -r .version version.json)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    - name: Build
      run: dotnet build --no-restore --configuration ${{ inputs.build_configuration }} ${{ env.SOLUTION_NAME }}

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ inputs.build_configuration }} ${{ env.SOLUTION_NAME }}

    - name: Pack and Push
      run: dotnet pack --no-build --configuration ${{inputs.build_configuration }} -p:PackageOutputPath=../../output --version-suffix "${{ env.VERSION_SUFFIX }}" -p:PackageSource='${{ env.NUGET_SOURCE }}' -p:PushAfterPack=true -p:PackageApiKey='${{ secrets.NUGET_API_KEY }}'
