name: Test

on:
  workflow_call:
    inputs:
      solution_name:
        description: "Solution file to build and test"
        required: true
        type: string
    secrets:
      GH_TOKEN:
        description: "GitHub token with write permissions"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SOLUTION_NAME: ${{ inputs.solution_name }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Set Build Configuration (Release if main)
        run: |
          if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
            echo "BUILD_CONFIGURATION=Release" >> $GITHUB_ENV
          else
            echo "BUILD_CONFIGURATION=Debug" >> $GITHUB_ENV
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN || github.token }}
          fetch-depth: 0  

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Restore Dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_NAME }}

      - name: Run Tests
        run: |
          mkdir -p TestResults
          found=false
          for proj in $(find . -name "*.Tests.csproj"); do
            found=true
            frameworks=$(grep -oPm1 "(?<=<TargetFrameworks>)[^<]+" "$proj" || true)
            if [ -z "$frameworks" ]; then
              frameworks=$(grep -oPm1 "(?<=<TargetFramework>)[^<]+" "$proj" || true)
            fi
            for fw in $(echo $frameworks | tr ';' ' '); do
              results_dir="./TestResults/$fw"
              mkdir -p "$results_dir"
              dotnet test "$proj" \
                --no-build \
                --configuration ${{ env.BUILD_CONFIGURATION }} \
                --framework $fw \
                --logger "trx;LogFileName=$(basename $proj)-$fw.trx" \
                --results-directory "$results_dir"
            done
          done
          if [ "$found" = false ]; then
            echo "⚠️ No test projects (*.Tests.csproj) found."
            exit 1
          fi

      - name: Upload .NET 9.0 Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-net9.0
          path: ./TestResults/net9.0/**/*.trx
          overwrite: true
          if-no-files-found: ignore

      - name: Upload .NET 8.0 Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-net8.0
          path: ./TestResults/net8.0/**/*.trx
          overwrite: true
          if-no-files-found: ignore
