name: Unlist NuGet Package (Shared)

on:
  workflow_call:
    inputs:
      package_id:
        description: "NuGet package ID (e.g., MyCompany.MyLib)"
        required: true
        type: string
      package_version:
        description: "Exact version to unlist (e.g., 1.2.3 or v1.2.3-alpha-abc123)"
        required: true
        type: string
      reason:
        description: "Optional reason for audit logs"
        required: false
        type: string
      dry_run:
        description: "If true, prints the command without executing"
        required: false
        default: false
        type: boolean
    secrets:
      NUGET_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  unlist:
    runs-on: ubuntu-latest
    env:
      PACKAGE_ID:   ${{ inputs.package_id }}
      RAW_VERSION:  ${{ inputs.package_version }}
      REASON:       ${{ inputs.reason }}
      DRY_RUN:      ${{ inputs.dry_run }}
      NUGET_SOURCE: https://api.nuget.org/v3/index.json

    steps:
      - name: Normalize + validate version
        id: semver              # ← always run (even in dry-run) so we can verify inputs
        run: |
          # (same script as before) …

      - name: Dry-run summary
        if: ${{ env.DRY_RUN == 'true' }}
        run: |
          echo "[DRY RUN] Would execute:"
          echo "dotnet nuget delete \"$PACKAGE_ID\" \"$NORMALIZED_VERSION\" --source \"$NUGET_SOURCE\" --api-key *** --non-interactive --force-english-output"
          # Exit with 0 so the job is marked ‘Succeeded’
          exit 0

      - name: Unlist on nuget.org
        if: ${{ env.DRY_RUN != 'true' }}   # ← **skip when dry_run=true**
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          set -euo pipefail
          echo "Unlisting ${PACKAGE_ID} ${NORMALIZED_VERSION} ..."
          dotnet nuget delete "$PACKAGE_ID" "$NORMALIZED_VERSION" \
            --source "$NUGET_SOURCE" \
            --api-key "$NUGET_API_KEY" \
            --non-interactive \
            --force-english-output
          echo "Successfully unlisted ${PACKAGE_ID} ${NORMALIZED_VERSION}"

      - name: Log reason (optional)
        if: ${{ env.REASON != '' && env.DRY_RUN != 'true' }}   # ← skip in dry-run
        run: echo "Reason - $REASON"

